import { Router } from "express";
import {
  createNewShortURL,
  deleteURL,
  getAllURLs,
} from "../Controllers/url.controllers.js";
import { verifyJWT } from "../Middlewares/auth.middleware.js";

const router = Router();

// get all urls generated by a user
router.get("/get", verifyJWT, getAllURLs);

// generate new url
router.post("/new", verifyJWT, createNewShortURL);

// delete the url
router.post("/delete", verifyJWT, deleteURL);

export default router;
