import { Router } from "express";
import {
  createNewShortURL,
  deleteURL,
  getAllURLs,
  handleRedirect,
} from "../Controllers/url.controllers.js";

const router = Router();

// get all urls generated by a user
router.get("/get", getAllURLs);

// generate new url
router.post("/new", createNewShortURL);

// delete the url
router.post("/delete", deleteURL);

// redirect
router.get("/redirect/:shortURL", handleRedirect);

export default router;
